Repository OS-EDU/os-edu.github.io, pull requests merged in 2021-03, with the labels that each got.

#40 [PAT - B1041] 更新 PAT-B1004.成绩排名 题解 Blog
  content/posts/PAT-B1004.md
Labels: add blog

#41 [Add Workflow] 增加 issue 和 pr 规范模板
  .github/ISSUE_TEMPLATE/add_questions.md
  .github/ISSUE_TEMPLATE/solutions.md
  .github/pull_request_template.md
Labels: enhancement

#44 [PAT - B1028] 更新 PAT-B1028.人口普查 题解 Blog
  content/posts/PAT-B1028.md
Labels: add blog

#46 [PAT - B1032] 更新 PAT-B1032.挖掘机技术哪家强 题解 Blog
  content/posts/PAT-B1032.挖掘机技术哪家强.md
Labels: add blog

#47 [Typos] PAT-B1032.挖掘机技术哪家强.md
  content/posts/PAT-B1032.挖掘机技术哪家强.md
Labels: Revise typos, fix wrong, update blog

#49 [PAT - B1032] 更新 PAT-B1022.D 进制的 A + B 题解 Blog
  content/posts/PAT-B1022.D 进制的 A + B.md
Labels: add blog
